baseURL = "http://www.bitcoin-lyon.fr/"
languageCode = "fr"
title = "Bitcoin à Lyon"
defaultContentLanguage = "fr"
enableEmoji = true
watch = true

[menu]

# Main menu

[[menu.main]]
    identifier="index"
    name = "Accueil"
    url  = "/"
    weight = 1

[[menu.main]]
    identifier="learn"
    name = "Qu'est-ce que Bitcoin ?"
    url  = "/apprendre/"
    weight = 2

[[menu.main]]
    identifier = "buy"
    name = "Achat de bitcoins"
    url  = "/achat/"
    weight = 3

[[menu.main]]
    identifier = "shop"
    name = "Boutique"
    url  = "/boutique/"
    weight = 4

[[menu.main]]
    identifier = "contact"
    name = "Contact"
    url  = "/contact/"
    weight = 5

# Top bar social links menu

[[menu.topbar]]
    weight = 1
    name = "GitHub"
    url = "https://github.com/leonodteam/bitcoin-lyon"
    pre = "<i class='fa fa-2x fa-github'></i>"

[[menu.topbar]]
    weight = 2
    name = "Facebook"
    url = "https://fr-fr.facebook.com/pg/LeonodTeam/posts/"
    pre = "<i class='fa fa-2x fa-facebook'></i>"

[[menu.topbar]]
    weight = 3
    name = "Twitter"
    url = "https://twitter.com/leonodteam"
    pre = "<i class='fa fa-2x fa-twitter'></i>"

[[menu.topbar]]
    weight = 4
    name = "Email"
    url = "contact@leonod.com"
    pre = "<i class='fa fa-2x fa-envelope'></i>"

[params]
    viewMorePostLink = "/"
    author = "Leonod"
    defaultKeywords = ["Bitcoin", "Blockchain", "Crypto"]
    defaultDescription = "Bitcoin à Lyon"

    # Twitter
    twitter = "LeonodTeam"
    twitterImage = "img/twitter-default.png"

    # Google Maps API key (if not set will default to not passing a key.)
    googleMapsApiKey = "AIzaSyCFhtWLJcE30xOAjcbSFi-0fnoVmQZPb1Y"

    # Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
    style = "orange"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
    #
    # Enable the contact form by entering your Formspree.io email
    email = "your@email.com"
    contact_form_ajax = false

    about_us = "Retrouvez nous sur <a href=\"https://leonod.fr\">Leonod.fr</a><br/>Retrouvez une communauté locale dévouée sur <a href=\"https://crypto-lyon.fr\">Crypto Lyon.fr</a>"
    copyright = "Copyright (c) 2019 <a href=\"https://leonod.fr\">Leonod</a>; all rights reserved."

    # Format dates with Go's time formatting
    date_format = "2 January 2006"

    logo = "img/logo.png"
    logo_small = "img/logo.png"
    address = "15 Place Jules Ferry, 69006 Lyon"
    latitude = "45.7682109"
    longitude = "4.8596369"

[Permalinks]
    blog = "/blog/:year/:month/:day/:filename/"

# Enable or disable top bar with social icons
[params.topbar]
    enable = true
    text = """<p class="hidden-sm hidden-xs">Vous pouvez nous contacter au 0437242338 ou nous retrouver sur <a href="https://leonod.fr">le site de Leonod</a>.</p>
      """

# Enable and disable widgets for the right sidebar
[params.widgets]
    categories = false
    tags = false
    search = false

[params.carousel]
    enable = true
    # cf 'data/carousel/*'

[params.features]
    enable = true
    # cf 'data/features/*'

[params.testimonials]
    enable = false

[params.see_more]
    enable = true
    icon = "fa fa-btc"
    title = "Tenter l'expérience Bitcoin"
    subtitle = "Vous pouvez acheter des bitcoins via notre site, ou à notre point physique"
    link_url = "#"
    link_text = "acheter des bitcoins"

[params.clients]
    enable = false

[params.recent_posts]
    enable = true
    title = "A propos de nous"
    subtitle = """Membres et animateurs de communautés locales, nous nous sommes professionnalisés et fournissons des services aux entreprises sur <a href=\"https://leonod.fr\">Leonod.fr</a> (développement, consulting) et des services aux particuliers sur <a href=\"www.bitcoin-lyon.fr\">Bitcoin-lyon</a> (vente de bitcoins et de produits dérivés). Nous sommes également membres de la communauté lyonnaise <a href=\"https://crypto-lyon.fr\">Crypto Lyon</a>."""
